### ISSUE TITLE
df.collect can not be executed twice when AE enabled

### ISSUE THREAD

**Issue by windpiger** [Intel-bigdata/spark-adaptive#66]
val x = spark.sql("select xxx")
x.collect
x.collect => Exception:

```
java.lang.UnsupportedOperationException
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doProduce(WholeStageCodegenExec.scala:648)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:88)
  at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:160)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:157)
  at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:83)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.produce(WholeStageCodegenExec.scala:498)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doCodeGen(WholeStageCodegenExec.scala:524)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:576)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:136)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:160)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:157)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:252)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:299)
  at org.apache.spark.sql.execution.adaptive.QueryStage.executeCollect(QueryStage.scala:176)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3278)
  at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2727)
```

the reason is that, CollapseCodegenStages will be executed in QueryStage  everytime when we call x.collect, so the second time we will insert one more WholeStageCodegenExec, we will get
WholeStageCodegenExec(child=WholeStageCodegenExec)

**Comment by carsonwang** [comment]
Fixed by #70
